config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: "posts#index"
  # resources :posts
  # resources :comments, only: [:new, :create]

  # resources :comments, only: [:destroy, :edit, :update]
  # get "forbidden", to: 'posts#forbidden'
  # resources :likes, only: [:create, :destroy]


  namespace :api, defaults: { format: :json } do
    namespace :v1 do

      resources :posts, only: [:index, :show, :create, :destroy, :update]
      resources :items, only: [:index, :show, :create, :destroy, :update]
      resources :comments, only: [:create, :destroy, :show, :index]
      resources :likes, only: [:create, :destroy, :index, :show]
      resources :carts, only: [:create, :destroy, :show, :update]
      resources :cart_items, only: [:create, :destroy, :update]

      get 'carts/:id/submit', to: 'carts#submit'
      get 'carts/:id/info', to: 'carts#info'

      get 'category/:id/:info', to: 'categories#info', constraints: lambda { |req| %w[tax_fee min_legal_age discount code].include? req.params[:info]}
    end
  end

  devise_for :users,
             controllers: {
               sessions: 'users/sessions',
               registrations: 'users/registrations'
             }
  get '/member-data', to: 'members#show'

end

app/views/shared/_navbar.html.erb
<nav class="flex justify-between px-60 py-10 items-center bg-gradient-to-r from-yellow-400 via-red-500 to-pink-500">
  <%= link_to "Really Good Blog", root_path, class: "text-xl text-gray-800 font-bold" %>

  <div class="flex items-center">
    <div class="flex items-center">
      <%= form_tag posts_path, method: :get do %>
                      <%= text_field_tag :query,
                      params[:query],
                      class: "form-control rounded-lg px-4  ml-2 outline-none bg-transparent font- ",
                      placeholder: "Find a post"
                      %>

                    <% end %>
    </div>
    <ul class="flex items-center space-x-6">
      <li class="font-semibold text-gray-700">
        <% if user_signed_in? %>
          <%= link_to "Log Out", destroy_user_session_path, :method=>'delete', class: "bg-indigo-800 text-white rounded-lg w-auto px-2 py-2 text-center"%>
        <% else %>
          <%= link_to "Login", new_user_session_path, class: "bg-indigo-800 text-white rounded-lg w-auto mx-6 px-2 py-2 text-center" %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_post_form.html.erb
<%= form_for(@post) do |f| %>
<div class="editor mx-auto w-10/12 flex flex-col text-gray-800 border border-gray-300 p-4 shadow-lg max-w-2xl bg-gray-800 rounded-lg border-gray-900">
  <%= f.text_field :title, class:"title bg-gray-100 border border-gray-300 p-2 mb-4 outline-none", placeholder: "Title" %>
   <%= f.text_area :content, class: "description bg-gray-100 sec p-3 h-60 border border-gray-300 outline-none", placeholder: "Describe everything about this post here" %>
  <div class="buttons flex mt-2">

    <%= link_to "Cancel", root_path, class: "btn border bg-gray-300 p-1 px-4 rounded cursor-pointer text-gray-500 ml-auto" %>
    <div class="actions btn border border-indigo-800 p-1  px-4  font-black rounded-lg cursor-pointer text-white ml-2 bg-indigo-800">
      <%= f.submit "Post" %>
    </div>
    <%end  %>
  </div>
</div>