config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: "posts#index"
  # resources :posts
  # resources :comments, only: [:new, :create]

  # resources :comments, only: [:destroy, :edit, :update]
  # get "forbidden", to: 'posts#forbidden'
  # resources :likes, only: [:create, :destroy]


  namespace :api, defaults: { format: :json } do
    namespace :v1 do

      resources :posts, only: [:index, :show, :create, :destroy, :update]
      resources :items, only: [:index, :show, :create, :destroy, :update]
      resources :comments, only: [:create, :destroy, :show, :index]
      resources :likes, only: [:create, :destroy, :index, :show]
      resources :carts, only: [:create, :destroy, :show, :update]
      resources :cart_items, only: [:create, :destroy, :update]

      get 'carts/:id/submit', to: 'carts#submit'
      get 'carts/:id/info', to: 'carts#info'

      get 'category/:id/:info', to: 'categories#info', constraints: lambda { |req| %w[tax_fee min_legal_age discount code].include? req.params[:info]}
    end
  end

  devise_for :users,
             controllers: {
               sessions: 'users/sessions',
               registrations: 'users/registrations'
             }
  get '/member-data', to: 'members#show'

end

app/models/post.rb
class Post < ApplicationRecord
  enum status: [:active, :inactive, :forbidden]
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :likes, as: :likeable


end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::BaseController
  before_action :set_post, only: [:show, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show

  end

  def create

    @post = Post.new(post_params)
    @post.date = Time.now


    if @post.save
      render json: @post, status: :created
    else
      render json: @post.errors, status: :unprocessable_entity
    end
  end


  def update
    @post.update(post_params)
    if @post.save
      render json: @post, status: :created
    else
      render json: @post.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @post.status = 'forbidden'
    if @post.save
      render json: @post, status: :created
    else
      render json: @post.errors, status: :unprocessable_entity
    end
  end



  private

  def set_post
    @post = Post.find_by(id: params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :user_id, :id)
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :forbidden]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like]

  def index
    if params[:query].present?
      sql_query = 'title ILIKE :query OR content ILIKE :query'
      @posts = Post.active.where(sql_query, query: "%#{params[:query]}%")
    else
      @posts = Post.active.order(created_at: :desc)
    end
  end



  def forbidden
    if params[:query].present?
      sql_query = 'title ILIKE :query OR content ILIKE :query'
      @posts = Post.forbidden.where(sql_query, query: "%#{params[:query]}%")
    else
      @posts = Post.forbidden.order(created_at: :desc)


    end
    render :index
  end


  def new

    @post = Post.new
    authorize @post
  end

  def edit
    authorize @post
  end

  def update
    authorize @post
    @post.update(post_params)
    @post.save
    redirect_to post_path(@post)
  end

  def show

  end

  def destroy
    authorize @post
    @post.status = 'forbidden'
    @post.save
    redirect_to :root
  end

  def search
  end

  def create
    @post = Post.new(post_params)
    @post.date = Time.now
    @post.user = current_user
    authorize @post
    if @post.save
      redirect_to :root
    else
      render :new
    end
  end

  private

  def set_post
    @post = Post.find_by(id: params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end

end

app/views/posts/edit.html.erb
<div class="heading text-center font-bold text-2xl m-5 text-gray-800">Edit Post</div>
<%= render 'shared/post_form' %>

app/views/posts/index.html.erb
<div class="columns-1 ">
  <div class="flex justify-center  w-screen items-start min-h-screen bg-gradient-to-r from-yellow-400 via-red-500 to-pink-500">
    <div class=" bg-gray-900 border-4 border-blue-900 items-start rounded-3xl w-11/12 max-h-4/6 md:w-9/12 md:max-h-5/6 overflow-y-auto">
      <section class="container mx-auto p-6 font-mono max-h-5/6 overflow-y-auto">
        <div class="w-full mb-8 overflow-y-auto rounded-lg shadow-lg">
          <div class="w-full overflow-x-auto max-h-128">
            <table class="w-full max-h-5/6 overflow-y-auto overflow-x-auto table-auto">
              <div class="flex justify-between items-center py-4">
                <h3 class="text-xl text-white"> <%= @posts.count %> Posts</h3>
                <div>
                  <% if policy(Comment).create? %>
                    <%= link_to "New Post", new_post_path, class:"bg-yellow-500 rounded-lg w-auto px-2 py-3 text-center" %>
                  <% end %>
                </div>
              </div>
              <thead>
                <tr class="text-md font-semibold tracking-wide text-left text-gray-900 bg-gray-100 uppercase border-b border-gray-600">
                  <th class="px-4 py-3">Title</th>
                  <th class="px-4 py-3">Author</th>
                  <th class="px-4 py-3">Publish Date</th>
                  <th class="px-4 py-3">Comments</th>
                  <th class="px-4 py-3">Actions</th>
                </tr>
              </thead>
              <tbody class="bg-white">
              <% @posts.each do |post| %>
                <tr class="text-gray-700">
                  <td class="px-4 py-3 border">
                    <div class="flex items-center text-sm">
                      <div>
                        <p class="font-semibold text-black"><%= post.title %></p>
                      </div>

                    <!-- test for status-->
                      <div>
                        <p class="font-semibold text-black"><%= post.status %></p>
                      </div>


                    </div>
                  </td>
                  <td class="px-4 py-3 text-ms font-semibold border"><%= post.user.username %></td>
                  <td class="px-4 py-3 text-xs border">
                    <span class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-sm"> <%= post.created_at %></span>
                  </td>
                  <td class="px-4 py-3 text-xs border">
                    <span class="font-semibold text-black">  <%= post.comments.count %></span>
                  </td>
                  <td class="px-4 py-3 text-sm border ">
                    <div class="h-full flex flex-wrap">
                      <% if policy(post).edit? %>
                        <%= link_to "Edit", edit_post_path(post) %>
                      <%end %>
                      <% if policy(post).destroy? %>
                        <%= button_to 'Delete', post, method: :delete %>
                      <%end %>
                     
                      <%= link_to "Show", post_path(post) %>

                    </div>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="heading text-center font-bold text-2xl m-5 text-gray-800">New Post</div>
<%= render 'shared/post_form' %>

app/views/posts/show.html.erb
<div class="flex justify-center items-start w-screen h-screen bg-gradient-to-r from-yellow-400 via-red-500 to-pink-500">
  <main class="relative items-start container mx-auto bg-white px-4 justify-center items-center rounded-lg">
    
    <article class="max-w-64 mx-16 py-8 text-center">
      <h1 class="text-3xl font-bold"><%= @post.title %></h1>
      <h2 class="mt-2 text-sm text-gray-500"><%= @post.created_at %></h2>
      <div class="text-left text-black">
        <% if policy(@post).edit? %>
          <%= link_to "Edit", edit_post_path(@post), class: "bg-gray-700 text-white font-bold py-2 px-4 w-full rounded hover:bg-gray-600" %>
        <%end %>
        <% if policy(@post).destroy? %>
          <%= link_to "Delete", @post, method: :delete, data: { confirm: 'Are you sure?'}, class: "bg-gray-700 text-white font-bold py-2 px-4 w-full rounded hover:bg-gray-600" %>
        <%end %>
      </div>
      <p class="my-8"> <%= @post.content %></p>
      <div class="flex justify-between items-center">
        <h1 class="text-2xl font-bold">Comments</h1>
        <%= link_to 'Comment', new_post_comment_path(@post), class: "bg-gray-700 text-white font-bold py-2 my-8 px-4 w-auto rounded hover:bg-gray-600" %>
      </div>
    <ul class="list-group">
      <% @post.comments.each do |comment| %>
        <div class="flex justify-between">
          <div>
            <li class="list-group-item text-left py-4 flex "> <h1>◆</h1><%= comment.content %>
          </li>
            <p class="text-left text-gray-700"> -- <%= comment.user.username %> </p>
          </div>
          <div class="align-middle">
            <% if policy(comment).destroy? %>
            <%= button_to 'remove', comment, method: :delete, class: "bg-gray-700 text-white font-bold py-2 px-4 w-full rounded hover:bg-gray-600 align-middle justify-self-end" %>
            <% end %>
          </div>
        </div>
      <% end %>
    </ul>
    </article>


  </main>
</div>